name: tutorial
channels:
  - defaults
dependencies:
  - python=2.7
  - pip:
    - mlflow
    - numpy=1.14.3
    - kafka-python==1.4.3
    - pyspark==2.3.1
    - pandas=0.22.0
    - scikit-learn=0.19.1
